### ISSUE TITLE
Bug in pip installation if numpy is not already installed

### ISSUE THREAD

**Issue by Astrokiwi** [pynbody/pynbody#563] opened 2020-06-16 18:46 UTC
pynbody should require numpy to be installed before running setup.py. Currently it assumes numpy is already installed - which may not be the case on new systems (i.e. when calling `pip install pynbody scipy numpy pandas matplotlib` or whatever).

Error:

`Collecting pynbody
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/fb/90/a97b5ccfd4b392c6f6b0fc0dff86fa8810ee80789009627cb9110ac09968/pynbody-0.47.tar.gz (2.5MB)
    100% |################################| 2.5MB 528kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5ooms4w8/pynbody/setup.py", line 4, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5ooms4w8/pynbody/
`

**Comment by rokroskar** [comment] 2020-06-17 11:33
Hmm you're right - the `pyproject.toml` was supposed to fix this but apparently it doesn't work as intended.

**Comment by rokroskar** [comment] 2020-06-17 12:12
@apontzen looks like `pyproject.toml` is not included in the package - though it is in `MANIFEST.in` and when I run `python setup.py sdist` I get 

```
❯ ls pynbody-0.48
PKG-INFO       docs           nose           pynbody        pyproject.toml setup.py
```

How are the releases packaged and pushed to PyPI? I guess it's done by hand?

**Comment by apontzen** [comment] 2020-06-17 12:30
I use `sdist upload` so I am confused about why this would not have worked. I'll try with a new release.

**Comment by rokroskar** [comment] 2020-06-17 12:35
From what I can see it never really worked properly, though I was pretty convinced I tried to install pynbody in a docker container before and that it had worked...

**Comment by Astrokiwi** [comment] 2020-06-17 12:38
I think that it doesn't come up much because everybody just installs numpy first anyway - it's at a deeper level in Maslow's Hierarchy of Needs. This is the fourth computer I've installed pynbody on and it's the first time I've encountered it. It's not a critical issue and it's easy to work around, but I guess it could be a source of confusion for some new PhD student trying to install something at home or something

**Comment by rokroskar** [comment] 2020-06-17 12:39
@Astrokiwi thanks for bringing this up, it clearly never was configured properly! In the meantime, what you can do is install from git like this:

```
pip install git+https://github.com/pynbody/pynbody
```

If you want to install a specific version instead of the latest master you can do something like

```
pip install git+https://github.com/pynbody/pynbody@v0.47
```

**Comment by Astrokiwi** [comment] 2020-06-17 12:45
In the end I basically just did:

    pip install numpy
    pip install pynbody

So it wasn't a huge time waster - I figure you guys would want to have this tidied away though anyway.

**Comment by rokroskar** [comment] 2020-06-17 12:46
I agree, the workaround is not difficult but it's annoying if e.g. included in a Dockerfile or indeed if a new user is faced with a strange error where they aren't expecting one.

**Comment by apontzen** [comment] 2020-06-17 13:20
I tried uploading a new version to pypi with the toml file in but it still doesn't seem to work - I tried a fresh install and hit the exact same problem. Any ideas?

**Comment by rokroskar** [comment] 2020-07-07 22:36
Which version of `pip` and python? I just tried this:

```
docker run --rm -ti python bash
$ pip install pynbody
```

and it works fine. Also works with the `3.6` and `3.7` images. The `pip` version is `20.1.1`.

**Comment by apontzen** [comment] 2020-07-08 21:16
I agree, it does seem to work now. I re-verified with ubuntu 

```
docker run --rm -ti ubuntu bash 
root@c76e7da1b179:/# apt-get update > /dev/null 
root@c76e7da1b179:/# apt-get install -y python3 python3-pip > /dev/null
root@c76e7da1b179:/# pip3 install pynbody
```

All seems fine. I’m not sure what happened before, perhaps an issue with the cache. I’m going to close this issue now as it seems to be fixed.

**Closed by apontzen** 2020-07-08 21:16 UTC
