### ISSUE TITLE
Strange issue with from . import backcompat

### ISSUE THREAD

**Issue by jobovy** [pynbody/pynbody#260] opened 2015-07-30 02:46 UTC
I'm having a weird issue with the line

    from . import backcompat

in ``pynbody/__init__.py`` in my travis builds for galpy since today (everything worked fine yesterday). See for example [here](https://travis-ci.org/jobovy/galpy/jobs/73304480#L2047). Everything works fine for me locally, and I don't really see what the issue could be. Seems like you merged a big pull request yesterday, and perhaps you have an idea of what could be going on here? I'm using miniconda on travis and install pynbody from master.

**Comment by apontzen** [comment] 2015-07-30 06:53
Bizarre - I have not seen this and as you can see our own tests are passing. Plus `backcompat` and its dependencies have not been touched in over a year. Can you reproduce it on a local machine and investigate interactively to see what has actually failed?

**Comment by rokroskar** [comment] 2015-07-30 07:59
yes this was indeed an issue at some point -- see comments around May 15 on PR #248, [this travis build](https://travis-ci.org/pynbody/pynbody/jobs/62673895), and [this commit that might be related]( 
https://github.com/pynbody/pynbody/commit/6a16687bcef072a0af5aef45bf8ef08f19fec440)

I remember the error ended up being somewhere else, even if it looked like it was coming from `backcompat.py`...

**Comment by jobovy** [comment] 2015-07-30 16:10
Thanks for the pointers! I played around a bit, but I still have no idea what is going wrong (can't reproduce this on my own machine), but am just dealing with it for now by installing the pynbody commit just before your latest merge: [diff](https://github.com/jobovy/galpy/commit/7cc1ae4116759f1a0f752219dbc21655146a306b#diff-354f30a63fb0907d4ad57269548329e3). Hopefully this will sort itself out in the future. Feel free to close.

**Comment by apontzen** [comment] 2015-08-03 08:41
Does your travis environment make any pynbody config adjustments? There is another importing problem, possibly related, at issue #261

**Comment by jobovy** [comment] 2015-08-03 14:01
Nope, I just do

    pip install git+git://github.com/pynbody/pynbody.git

No changes to the config or anything...

**Comment by apontzen** [comment] 2015-08-04 11:33
Bit of a stab in the dark but I think it might be because an h5py dependence has been snuck in. Could you try doing your travis build with revision  53dcd5b1243a8b? Tx.

**Comment by jobovy** [comment] 2015-08-04 12:48
What's the full hash of this revision? Pip cannot find it and neither can I looking through the commits...

**Comment by apontzen** [comment] 2015-08-04 14:21
My bad, the commit is actually 60485bbf1ff77a3834

**Comment by jobovy** [comment] 2015-08-04 15:45
That seems to have worked! Absurd that that was the issue, but I guess that was it.

**Comment by apontzen** [comment] 2015-08-04 18:00
Great. I have merged it in.

**Closed by apontzen** 2015-08-04 18:00 UTC

**Comment by jobovy** [comment] 2015-08-04 18:03
Thanks! I'm glad it turned out to be an interesting failure mode after all!
