### ISSUE TITLE
np.empty returns a predetermined array after centering

### ISSUE THREAD

**Issue by M1ssing-N0** [pynbody/pynbody#861] opened 2024-11-07 14:12 UTC
**Describe the bug**
After centering of a snapshot using pynbody.analysis.halo.center, np.empty starts to generate arrays with the same values as the center coordinates or its absolute values, if the dimension of both arrays share the same dimensions (e.g., np.empty(3) will be affected if a three dimensional snapshot was centered)

**To Reproduce**
```
a = np.empty(3)
print(a)
cen = pynbody.analysis.halo.center(h[0])
a = np.empty(3)
print(a)
a = np.empty(3)
print(a)
```

**Expected behaviour or result**
For the test data, the output is
```
[0. 0. 0.]
[ 0.02445641 -0.03411335 -0.12243617]
[0.02445641 0.03411335 0.12243617]
```

**Setup (please complete the following information):**
  - OS: Linux-6.6.54-2-MANJARO-x86_64-with-glibc2.40
  - Python version: 3.12.6
  - Numpy version: 1.26.4
  - Pynbody version: 1.6.0.post0

**Comment by apontzen** [comment] 2024-11-07 14:19
I think this is expected behaviour. According to https://numpy.org/doc/stable/reference/generated/numpy.empty.html: 

Return a new array of given shape and type, _without initializing entries._

(emphasis added)

It doesn't surprise me that numpy would reuse recently deallocated memory and, since it doesn't initialise it, you just see the value that was there before. 

Certainly I don't think this is a bug in pynbody, so am I ok to close it?

**Closed** 2024-11-07 19:48 UTC
