### ISSUE TITLE
Unit test fail in python3 with type errors

### ISSUE THREAD

**Issue by jakobherpich** [pynbody/pynbody#390] opened 2017-06-27 13:22 UTC
The following unit tests fail with `TypeError`s when I call them with `nosetests3`:
gadgethdf_test.py
halotools_test.py
snapshot_test.py
sph_image_test.py
utils_test.py

The error message is either:
```
TypeError: slice indices must be integers or None or have an __index__ method
```
or
```
TypeError: 'float' object cannot be interpreted as an integer
```

For some reason they pass the tests during pull requests but not those on my local machine. However, I do not understand how the TravisCI tests are implemented? Is TravisCI running the tests from the nose/ directory?

I won't be able to look into this anytime soon so someone else needs to do it.

**Comment by apontzen** [comment] 2017-07-05 15:13
Unfortunately I can't reproduce this... will keep it open and wait for more information

**Comment by apontzen** [comment] 2017-07-13 17:07
@jakobherpich I managed to reproduce this with py3 and the latest version of numpy, and think it should be fixed in the latest master branch - could you check?

**Comment by jakobherpich** [comment] 2017-07-14 19:31
Unfortunately not soon. I'm traveling until end of July without computer access.

**Comment by apontzen** [comment] 2017-09-18 16:42
Closing this issue as is believed to be fixed. Please re-open if I am wrong!

**Closed by apontzen** 2017-09-18 16:42 UTC
Labels: bug
