### ISSUE TITLE
64-bit integers in starlog

### ISSUE THREAD

**Issue by emapple** [pynbody/pynbody#328] opened 2016-04-14 17:59 UTC
There is an error trying to read the starlog file using pynbody. It seems to be that our iord and iorderGas parameters use 64-bit integers, and pynbody can only handle 32-bit. Can this be fixed?

**Comment by apontzen** [comment] 2016-04-14 23:21
It can be fixed; the code you need to change is at line 1143 of tipsy.py (and underneath that in the alternative file formats). 

The harder thing is writing the heuristic to switch automatically. How do you decide whether to write 32 or 64 bit starlogs?

Also paging @mtremmel on this who I think may have seen similar problems in the past.

**Comment by mtremmel** [comment] 2016-04-15 15:02
Yes, I've thought about this and @apontzen is correct... the problem is working it into the code so that pynbody can automatically choose the correct file format. There is a degeneracy in the sizes of entries between having 32 bit iords with H2 information and 64 bit iords without H2.... thought needs to be put into this to ensure proper backwards compatibility.

The choice to move to 64 bit was made after we realized that our bigger simulations were overflowing their 32 bit iord values. Granted this is only an issue for really big simulations, it should still be properly handled. Moving to 64 bit is the correct choice and I think should be the norm from now on with ChaNGa.

**Comment by apontzen** [comment] 2016-04-19 08:53
@mtremmel @emapple Is there something in the .param file that indicates 64 bit will be used?

**Comment by mtremmel** [comment] 2016-04-19 15:00
I don't believe so.... I think it is a patch to the code. I can double check with Tom once he is in the office. Oh, but H2 physics *is* a parameter... so maybe that helps break the degeneracy?

The one complicated thing is that the latest versions of ChaNGa with my BHs does have one extra piece of data: the cooling time of the gas. I've edited my own copy of pynbody to handle this and normally it would still work fine with the master branch version (it would just read it as H2). I was hesitant to add this bit to master.... but maybe it is worth doing, especially as the BH branch of the code is made to be "normal". I was just worried about backward compatibility... 

For right now, if you are using data from ChaNGa + my BHs, then you can pull my "romulus" branch from my forked repository, which will have any patch for 64 bit iords merged once that's done (it just has a different "default" format if that makes sense)

**Comment by trquinn** [comment] 2016-04-19 15:25
The starlog change was a code change (made back in November), so there is no indication in the param or log file other than the version number, which would be hard to decipher.

**Comment by apontzen** [comment] 2016-07-25 20:08
Fixed by #340

**Closed by apontzen** 2016-07-25 20:08 UTC
