### ISSUE TITLE
" KeyError: 'iord' " When reading in halo file

### ISSUE THREAD

**Issue by gmetin** [pynbody/pynbody#578] opened 2020-09-02 09:50 UTC
**Describe the bug**
Hi,
I wanted to use pynbody to analyze my simulations.
Setup:
-) DM only sim with PKDRAV3, outputs are in Tipsy
-) Rockstar Halo finder on PKDGRAV snapshots

I read in the tipsy snapshot:
`s = pynbody.load('/path/sim.file')`

I find two things.
1) This is minor, `s.properties` does not give me redshift/scale factor information
2) I am not able to load halo files, that I previously calculated with Rockstar.

I copied the halo file in the same directory as the snapshot and did
`s.halos()`
and also tried 
`h = pynbody.halo.RockstarCatalogue(s,filenames=["/path/halo.file"])`

Both attempts take very long time and then finally error 

>  KeyError: 'iord'

Is there a way to get passed this error?
Thanks

**Comment by apontzen** [comment] 2020-09-02 10:12
Thanks for the report. Could you provide a link to files that allow this problem to be reproduced?

**Comment by gmetin** [comment] 2020-09-02 13:40
HI Andrew, 
thanks for the answer and your help.

I forgot to tell you that I also changed the units of the tipsy file to match physical units that Rockstar works in. But that was obviously not the problem.

`#%%`
`from astropy.cosmology import FlatLambdaCDM`
`import pynbody`
`from astropy import units as u`

`cosmo = FlatLambdaCDM(H0=100, Om0=0.31, Tcmb0=2.726)`
`#convert units to physical in pynbody`
`box_size=480`
`s['pos'] = s['pos']+0.5*box_size`
`s['pos'].units='Mpc'`
`#get speed of light in km/s`
`ckms = 299792`
`velkms = (box_size/8677.2079486362706)*ckms`
`s['vel']*=velkms`
`s['vel'].units='km s^-1'`
`#mass of particle`
`s['mass'] = s['mass']*(cosmo.critical_density0.to(u.M_sun/u.Mpc**3)*(box_size*u.Mpc)**3).value`

Find the halos at:
[https://drive.google.com/open?id=1qt5LIqawmamZTF4OwBsMbkmXpnmoQB2N](url)

Find the snapshot at (4.6 GB):
[https://drive.google.com/file/d/1n3XyFGdl_GrW5YzQtJ1oec2X5yAOLNxD](url)

**Comment by apontzen** [comment] 2020-09-02 19:40
The halos file you pointed to has only the `.ascii` output from rockstar, which has the stats but not the particle IDs of the halos. pynbody needs the full output (files with names like `halos*.bin` or `halosbound*.bin`). Could you provide these files?

**Comment by gmetin** [comment] 2020-09-03 00:45
Sorry, I actually tried to read in the `.bin` file. 

[https://drive.google.com/file/d/1kyMkX2nwWq1Ob1j2PxzZbe9RNRP6n1yk](url)

**Comment by apontzen** [comment] 2020-09-04 12:15
I have proposed a fix in PR #580 -  https://github.com/pynbody/pynbody/tree/rockstar-no-iords

Could you verify whether it works for you?

Note that I could only reproduce the exception, not the long runtimes that you reported. See below. I am not sure what runtimes you were expecting, or if you are seeing worse performance than this, but it seems reasonable to me given the amount of data shuffling involved.

```ipynb
In [1]: import pynbody                                                                                                                                                                                             

In [2]: %time f = pynbody.load("constrained_birth_1650_512.00100")                                                                                                                                                 
/Users/app/Science/pynbody/pynbody/snapshot/tipsy.py:130: RuntimeWarning: No readable param file in the run directory or parent directory: using defaults.
  "No readable param file in the run directory or parent directory: using defaults.", RuntimeWarning)
CPU times: user 102 ms, sys: 3.42 ms, total: 105 ms
Wall time: 104 ms

In [3]: %time h = f.halos()                                                                                                                                                                                        
/Users/app/Science/pynbody/pynbody/simdict.py:92: RuntimeWarning: Assuming default value for property 'a'=1.00e+00
  name, value), RuntimeWarning)
/Users/app/Science/pynbody/pynbody/halo/__init__.py:138: RuntimeWarning: No iord array available; assuming halo catalogue is using sequential particle IDs
  RuntimeWarning)
CPU times: user 5.61 s, sys: 1.87 s, total: 7.47 s
Wall time: 7.47 s
```

**Comment by gmetin** [comment] 2020-09-09 09:50
Thank you for the fix. 
I can read in the rockstar catalog now. 
However reading the catalog takes 10 minutes. Maybe it's a general anaconda problem, I don't know...

```
In [1]: import pynbody
In [2]: %time f = pynbody.load("constrained_birth_1650_512.00100")
/home/user/anaconda3/lib/python3.8/site-packages/pynbody/snapshot/tipsy.py:129: RuntimeWarning: No readable param file in the run directory or parent directory: using defaults.
  warnings.warn(
CPU times: user 56 ms, sys: 16 ms, total: 72 ms
Wall time: 251 ms

In [3]: %time h = f.halos()
/home/user/anaconda3/lib/python3.8/site-packages/pynbody/simdict.py:91: RuntimeWarning: Assuming default value for property 'a'=1.00e+00
  warnings.warn("Assuming default value for property '%s'=%.2e" % (
/home/user/anaconda3/lib/python3.8/site-packages/pynbody/halo/__init__.py:133: RuntimeWarning: No iord array available; assuming halo catalogue is using sequential particle IDs
  warnings.warn("No iord array available; assuming halo catalogue is using sequential particle IDs",
CPU times: user 12.7 s, sys: 9min 46s, total: 9min 58s
Wall time: 9min 59s
```

**Comment by apontzen** [comment] 2020-09-09 11:00
I can't reproduce this, I'm afraid. The time is being spent in `sys` not `user` so it suggests an underlying issue with the system you are running on?

**Comment by gmetin** [comment] 2020-09-09 11:02
Thank you again for your help. 
Yes, I guess it is an issue on my side.

**Comment by apontzen** [comment] 2020-09-11 19:06
Thanks, I'm merging the fix and closing this issue but if you do later find that the problematic performance can be fixed within pynbody feel free to reopen a new issue.

**Closed by apontzen** 2020-09-11 19:06 UTC
