### ISSUE TITLE
Ramses loading slower in Python 3.6.7 than 2.7.15

### ISSUE THREAD

**Issue by mkrets** [pynbody/pynbody#501] opened 2019-01-21 10:31 UTC
Hi,

I am using 2 environments (python 3.6.7 and 2.7.15).
For both of them:
```python
In [1]: import pynbody

In [2]: print(pynbody.__version__)
0.47

In [3]: pynbody.config['number_of_threads']
Out[3]: 8

In [4]: pynbody.openmp.get_cpus()
Out[4]: 8

In [5]: import posix_ipc

In [6]: posix_ipc.__version__
Out[6]: '1.0.4'
```
For python 2.7.15:
```python
In [7]: %time data = pynbody.load("bulk1/data_2/hydro_09/output/output_00050"); print(data.gas["mass"].sum().in_units("Msol"))
286632194068077.8
CPU times: user 1.64 s, sys: 1.16 s, total: 2.8 s
Wall time: 13.4 s
```

But for python 3.6.7:

```python

In [7]: %time data = pynbody.load("bulk1/data_2/hydro_09/output/output_00050"); print(data.gas["mass"].sum().in_units("Msol"))
286632194068077.8
CPU times: user 3.74 s, sys: 2.56 s, total: 6.3 s
Wall time: 11min 22s
```
(I also tried using posix_ipc version 1.0.0).
The snapshot has a total size of 1.9 Gb and was run on 288cpus.

Thank you in advance!

**Comment by mkrets** [comment] 2019-01-21 13:38
I edited the file, now it should contain the `part_00030.out...` files.

**Comment by apontzen** [comment] 2019-01-22 09:31
I confirm I can reproduce the basic issue. Will investigate further.

**Comment by apontzen** [comment] 2019-04-12 11:04
I don't think it's deadlocking, at least not on my setup. It's just that the operation is way slower, even when reading with a single processor.

**Comment by apontzen** [comment] 2019-04-12 11:21
The issue actually seems to be that there is a much bigger overhead on calls to `numpy.fromfile` in python 3 than in python 2.

```python
import contextlib
import numpy as np
import time
import sys

@contextlib.contextmanager
def timeme(label):
    start = time.time()
    yield
    end = time.time()
    diff = end-start
    print("%s: %.2es"%(label, diff))

py_version = sys.version_info[:2]

with timeme('one big read, py%d.%d'%py_version):
    with open('output_00030/amr_00030.out00096', 'rb') as f:
        np.fromfile(f, np.float32, 450000)

with timeme('lots of little reads, py%d.%d'%py_version):
    with open('output_00030/amr_00030.out00096', 'rb') as f:
        for i in range(1000):
            np.fromfile(f, np.float32, 450)
```

I get the following results:
```
one big read, py2.7: 7.61e-04s
lots of little reads, py2.7: 1.66e-03s
one big read, py3.6: 7.69e-04s
lots of little reads, py3.6: 1.45e-02s
```

i.e. there is a much bigger penalty to lots of little reads on py3.6 than on py2.7. Not entirely sure where to go from here, since it would be a huge change to try and read the complicated ramses format in larger chunks.

**Comment by apontzen** [comment] 2019-04-12 11:46
Further investigation using stack sampling suggests that the problem is here:
https://github.com/numpy/numpy/blob/9a39877b9f9761051a8f86a9cfff392660fa7189/numpy/core/include/numpy/npy_3kcompat.h#L172

Python 3 does not easily produce OS-level file descriptors from its own file objects. The workaround in numpy is hugely inefficient, producing a load of file operations every time `fromfile` is entered.

**Comment by apontzen** [comment] 2019-04-12 17:03
OK, I just reimplemented numpy's fromfile in a simple way. It seems to make performance a lot better for me - please could you check #517 to see if it helps you too @mkrets?

**Comment by mkrets** [comment] 2019-04-14 11:35
Thank you for looking into this!
I tried #517 , and the performance is enhanced.
Now loading the same data takes `Wall time: 7min 8s` instead of `~11min`.
Which is however not fast compared to python2.7.
Have you looked at numpys frombuffer or memmap or the [struct](https://docs.python.org/3/library/struct.html) package? 
If it's only a ramses problem, we could write a more specific loader.

**Comment by apontzen** [comment] 2019-04-14 11:38
Hmm, that's a disappointingly small gain. The problem is basically that IO has changed radically in Python 3, and numpy is performing acrobatics to get around it. I don't think you'll do better with frombuffer.

For sure it could be improved a lot by reducing the number of small loads in the ramses loader, probably by judicious use of appropriate datatypes rather than using the struct package, but I don't have time to do that right now (obviously it'd be great if you can!)

I opened a ticket about the underlying issue here: https://github.com/numpy/numpy/issues/13319

**Comment by apontzen** [comment] 2019-04-14 11:44
Actually, thinking about it some more I see what you mean about `frombuffer` - I guess you imagine reading large chunks of data ahead of time. It could work...

**Comment by apontzen** [comment] 2019-04-14 12:16
Your idea turns out to be super-easy to implement, at least in a simple way. Hopefully this gives better (but probably not yet optimal) performance. I have pushed it to the same branch; please give it a go and let me know.

**Comment by mkrets** [comment] 2019-04-14 12:38
That's a great improvement!
`Wall time: 42.8 s`

**Comment by apontzen** [comment] 2019-04-14 13:29
Great - could you check it on python 2 as well, to see whether it is
slower/faster than the original code there?

**Comment by mkrets** [comment] 2019-04-14 14:36
I don't notice a slowdown in python2, comparing master and #517.

**Comment by apontzen** [comment] 2019-04-14 20:06
Thanks for your help tracking this down and fixing. Merged to master.

**Closed by apontzen** 2019-04-14 20:06 UTC
Labels: enhancement
